import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const monto = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '900'],
  variable: '--font-monto'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={monto.className}>{children}</body>
    </html>
  );
}
